# -----------------------------------------------------------------------------
# File: config.toml
# Author: Zakaria Kebairia
# Date:   2025-05-07
# Version:1.7
# Description: Main configuration for bacli backup utility
# -----------------------------------------------------------------------------

# Include other config fragments (use .toml equivalents)
include = ["./configs/postgres.toml"]
# - "./configs/mongodb.toml"
# - "./configs/redis.toml"
# - "./configs/mysql.toml"

[vault]
address = "<vault address>"
token   = "<vault token>"

[backup]
output_dir       = "./backups"
compress         = true
timestamp_format = "2006-01-02_15-04-05"
timeout          = "30m"

[metadata]
path = "./metadata.json"

[retention]
keep_last        = 7
cleanup_interval = "24h"
