# =============================================================================
# File:        config.yaml
# Project:     bacli - Backup Utility
# Author:      Zakaria Kebairia
# Created:     2025-05-07
# Version:     1.7
# -----------------------------------------------------------------------------
# Description:
#   Main configuration file for the bacli backup utility.
#   This file defines global settings for Vault integration,
#   backup behavior, and retention policies.
# =============================================================================
# -----------------------------------------------------------------------------
# Included service-specific configurations
# -----------------------------------------------------------------------------
include:
  - ./configs/postgres.yaml
  # - ./configs/mongodb.yaml
  # - ./configs/redis.yaml
  # - ./configs/mysql.yaml
# -----------------------------------------------------------------------------
# Vault integration
# -----------------------------------------------------------------------------
vault:
  address: "https://vault.hl.lan:8200"
  # AppRole used for Vault auth
  approle: "backup-approle"
# -----------------------------------------------------------------------------
# Backup settings
# -----------------------------------------------------------------------------
backup:
  # Destination for backup files
  directory: "./backups"
  # Enable/disable compression
  compression: false
  # Timestamp pattern for file naming
  timestamp_fmt: "2006-01-02_15-04-05"
  # Backup execution timeout
  timeout: 30m
# -----------------------------------------------------------------------------
# Retention policy
# -----------------------------------------------------------------------------
retention:
  # Number of most recent backups to keep
  keep: 7
  # Cleanup check frequency
  interval: 24h
