# -----------------------------------------------------------------------------
# File: config.yaml
# Author: Zakaria Kebairia
# Date:   2025-05-07
# Version:1.7
# Description: Main configuration for bacli backup utility
# -----------------------------------------------------------------------------
include:
  - ./configs/postgres.yaml
  - ./configs/mongodb.yaml
  # - ./configs/redis.yaml
  # - ./configs/mysql.yaml
vault:
  address: "https://vault.hl.test:8200"
  role_id: "59627c2c-2906-7343-e580-cb2b3a785e94"
  role_name: "approle-backup"
backup:
  output_directory: "./backups"
  compress: true
  timestamp_format: "2006-01-02_15-04-05"
  timeout: 30m
retention:
  keep_last: 7
  cleanup_interval: 24h
