# -----------------------------------------------------------------------------
# Author:      Zakaria Kebairia
# Date:        2025-04-28
# Version:     1.4
# Description: Main configuration for backup utility.
# -----------------------------------------------------------------------------
include:
  - "./configs/postgres.yaml"
  - "./configs/mongodb.yaml"
vault:
  address: "http://127.0.0.1:8200"
  token: "root"
backup:
  output_dir: "./backups"
  compress: true
  timestamp_format: "2006-01-02_15-04-05"
  timeout: "30m"
metadata:
  path: "./metadata.json"
defaults:
  postgres:
    host: "localhost"
    port: "5432"
    method: "tar"
  mongodb:
    host: "localhost"
    port: "27017"
    method: "archive"
