# -----------------------------------------------------------------------------
# Author:      Zakaria Kebairia
# Date:        2025-04-28
# Version:     1.2
# Description: Main configuration for backup utility.
# -----------------------------------------------------------------------------
include:
  - "./configs/postgres.yaml"
  - "./configs/mongodb.yaml"
backup:
  # Directory where all backups are saved
  output_dir: "./backups"
  # Enable compression for backup archives
  compress: true
  # Go time layout for filenames
  timestamp_format: "2006-01-02_15-04-05"
metadata:
  # Where to write metadata.json
  path: "~/dox"
  # path: "../metadata.json"
  # Optional: compress metadata file (future feature)
  # compress: false
  # # Future-proof: allow "json", "yaml" metadata
  # format: "json"
defaults:
  postgres:
    # Default Postgres host
    host: "localhost"
    # Default Postgres port
    port: "5432"
    # Default backup method for Postgres
    method: "custom"
  mongodb:
    # Default MongoDB host
    host: "localhost"
    # Default MongoDB port
    port: "27017"
    # Default backup method for MongoDB
    method: "archive"
