# -----------------------------------------------------------------------------
# Description: MongoDB backup configuration
# -----------------------------------------------------------------------------
mongodb:
  host: "localhost"
  port: 27017
  timeout: 30m
  compress: true
  method: "archive" # mongodump modes: "archive" or directory
  vault:
    # kv_base: "secret/data/mongodb"
    role_base: "database/creds"
  instances:
    - name: "db1"
      host: "localhost"
      port: "27018"
      database: "testdb1"
      role_name: "mongo-db1-backup"
    - name: "db2"
      host: "localhost"
      port: "27019"
      database: "testdb2"
      role_name: "mongo-db2-backup"
    - name: "db3"
      host: "localhost"
      port: "27020"
      database: "testdb3"
      role_name: "mongo-db3-backup"
