# -----------------------------------------------------------------------------
# Author:      Zakaria Kebairia
# Date:        2025-05-02
# Version:     1.4
# Description: MongoDB instances for backup (credentials in Vault).
# -----------------------------------------------------------------------------
mongodb:
  vault_base_path: "secret/data/mongodb"
  instances:
    - name: "db1"
    - name: "db2"
    - name: "db3"
