# -----------------------------------------------------------------------------
# Description: MySQL backup configuration
# -----------------------------------------------------------------------------
mysql:
  host: "localhost"
  port: 3306
  timeout: 30m
  compress: true
  method: "dump" # mysqldump mode ("dump", "raw", ...)
  vault:
    kv_base: "secret/data/mysql"
    role_base: "database/creds"
  instances:
    - name: "db1"
      kv_path: "db1"
      role_name: "mysql-db1-backup"
    - name: "db2"
      kv_path: "db2"
      role_name: "mysql-db2-backup"
    - name: "db3"
      kv_path: "db3"
      role_name: "mysql-db3-backup"
