# =============================================================================
# File:        postgres.yaml
# Project:     bacli - Backup Utility
# Author:      Zakaria Kebairia
# Created:     2025-05-07
# Version:     1.0
# -----------------------------------------------------------------------------
# Description:
#   PostgreSQL backup configuration for bacli.
#   Defines global PostgreSQL backup defaults and instance-specific overrides.
# =============================================================================
postgres:
  # ---------------------------------------------------------------------------
  # Global defaults (can be overridden per instance)
  # ---------------------------------------------------------------------------
  host: "localhost"
  port: 5344
  # Execution timeout for pg_dump
  timeout: 30m
  # Enable/disable compression
  compression: false
  # Default database role name
  role: "pg"
  # pg_dump formats: plain|custom|directory|tar
  format: "custom"
  vault:
    # Vault path prefix for DB credentials
    creds_path: "database/creds"
  # ---------------------------------------------------------------------------
  # PostgreSQL instances
  # ---------------------------------------------------------------------------
  instances:
    - name: "keycloak"
      database: "keycloak"
      # Override default (uses plain format)
      format: "plain"
    - name: "jobboard admin"
      host: "localhost"
      port: 5344
      database: "jobboard_admin"
      # Inherits global default
      format: "directory"
