# -----------------------------------------------------------------------------
# Author:      Zakaria Kebairia
# Date:        2025-05-02
# Version:     1.4
# Description: PostgreSQL instances for backup (credentials in Vault).
# -----------------------------------------------------------------------------
postgres:
  vault_base_path: "secret/data/postgres"
  instances:
    - name: "db1"
    - name: "db2"
    - name: "db3"
